('HF1','1','Forestry','Input','Fruit Id', ''),
('HF1','2','Forestry','Input','Beneficary Name', ''),
('HF1','3','Forestry','Dropdown','Farmer Class', '["Small Farmer", "Marginal Farmer", "Others"]'),
('HF1','4','Forestry','Dropdown','Special Disable Person', '["Yes", "No"]'),
('HF1','5','Forestry','Dropdown','Minority','["Muslim", "Cristians", "Jain", "Buddhists","Sikhs", "Others"]'),
('HF1','6','Forestry','Dropdown','Gender', '["Male", "Female", "Others"]'),
('HF1','7','Forestry','Dropdown','Category','["General", "SCP", "TSP", "OBC", "Others"]'),
('HF1','8','Forestry','Input','Mobile Number', ''),
('HF1','9','Forestry','Input','Survey No', ''),
('HF1','10','Forestry','Dropdown','Type Of Land', '["Private Land"]'),
('HF1','11','Forestry','Input','Activity Name', ''),
('HF1','12','Forestry','Input','Subactivity Name', ''),
('HF1','13','Forestry','MultiCheck', 'Plant Name', '["Agava"]'),
('HF1','14','Forestry','Input','No. Of Plants',''),
('HF1','15','Forestry','Input','Unit in Ha',''),
('HF1','16','Forestry','Input','Unit in Nos',''),
('HF1','17','Forestry','Input', 'Scheme', ''),
('HF1','18','Forestry','Input', 'Sub Scheme', ''),
('HF1','19','Forestry','Dropdown', 'Districts', ''),
('HF1','20','Forestry','Dropdown', 'Taluka', ''),
('HF1','21','Forestry','Dropdown','Villages', ''),
('HF1','22','Forestry','DropDown','Grama Panchayat', ''),
('HF1','23','Forestry','Text', 'Project Name', ''), 
('HF1','24','Forestry','Input','MICRO WATER SHED', ''),
('HF1','25','Forestry','Dropdown', 'Financial Year', ''),
('HF1','26','Forestry','Dropdown', 'Status Of Work', '["Site Selection", "In Progress", "Completed"]'),
('HF1','27','Forestry','Date', 'Work Started', ''),
('HF1','28','Forestry','Date', 'Work Completed', ''),
('HF1','29','Forestry','Input', 'Estimated Cost', ''),
('HF1','30','Forestry','Input', 'Expenditure Number', ''),
('HF1','31','Forestry','Input', 'Latitude', ''),
('HF1','32','Forestry','Input', 'Longitude', ''),
('HF1','33','Forestry','Input', 'Out Put/Out Come', ''),
('HF1','34','Forestry','Input','Work Order Number', ''),
('HF1','35','Forestry','Input','Sanction Number', ''),					
('HF1','36','Forestry','MultiPhoto','GPS photos Of Nursery', '["Polybag Filling Photos","Nursery Seedling Raised Photos"]')



//["Teak","Silver Oak","Hebbevu","Jackfriut","Pongamia","Neem","Jamun","Custard Apple","Bamboo","Banyan Tree","Amla","Sandalwood","Mahagani","Mango","Tamarind","Cashew","Drumstick","Curry Leaf","Lime","Agase","Cluster fig" ,"Basari mara","Bael","Peepul tree","Agava","Gliricidia","Cassia Siamea","Butea monosperma" ,"Gasagase Tree","Gulmohar Tree","Hippe Tree","Honne","Tapsi","Terminalia arjuna (Hole Matthi)","Seeme Thangadi","Goose Berry","Others"]